### ISSUE TITLE
Invalid return value for `check_empty_value/2`

### ISSUE THREAD

**Issue by doofyus** [maiduule/gateway_elixir#2]
Method `check_empty_value/2` in here: https://github.com/maiduule/gateway_elixir/blob/d3c157a1156c4b501dc01ff78639dc5c6de9f246/apps/binary_proxy_server/lib/binary_proxy_server/command.ex#L126

Should output `{:ok, <<0x01, 0x05 ... <> value}` here:

https://github.com/maiduule/gateway_elixir/blob/d3c157a1156c4b501dc01ff78639dc5c6de9f246/apps/binary_proxy_server/lib/binary_proxy_server/command.ex#L132

**Comment by maiduule** [comment]
Fixed
